// Code generated by gocc; DO NOT EDIT.

package parser

type (
	actionTable [numStates]actionRow
	actionRow   struct {
		canRecover bool
		actions    [numSymbols]action
	}
)

var actionTab = actionTable{
	actionRow{ // S0
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			shift(2), /* package */
			nil,      /* str */
			nil,      /* empty */
			nil,      /* use */
			nil,      /* class */
			nil,      /* letters */
			nil,      /* { */
			nil,      /* } */
			nil,      /* : */
			nil,      /* struct */
			nil,      /* int */
			nil,      /* int32 */
			nil,      /* int64 */
			nil,      /* long */
			nil,      /* bool */
			nil,      /* short */
			nil,      /* uint */
			nil,      /* uint32 */
			nil,      /* uint64 */
			nil,      /* ulong */
			nil,      /* ubool */
			nil,      /* ushort */
			nil,      /* byte */
			nil,      /* string */
			nil,      /* char */
			nil,      /* float */
			nil,      /* double */
			nil,      /* [] */
			nil,      /* [ */
			nil,      /* integer */
			nil,      /* ] */
		},
	},
	actionRow{ // S1
		canRecover: false,
		actions: [numSymbols]action{
			nil,          /* INVALID */
			accept(true), /* $ */
			nil,          /* package */
			nil,          /* str */
			nil,          /* empty */
			nil,          /* use */
			nil,          /* class */
			nil,          /* letters */
			nil,          /* { */
			nil,          /* } */
			nil,          /* : */
			nil,          /* struct */
			nil,          /* int */
			nil,          /* int32 */
			nil,          /* int64 */
			nil,          /* long */
			nil,          /* bool */
			nil,          /* short */
			nil,          /* uint */
			nil,          /* uint32 */
			nil,          /* uint64 */
			nil,          /* ulong */
			nil,          /* ubool */
			nil,          /* ushort */
			nil,          /* byte */
			nil,          /* string */
			nil,          /* char */
			nil,          /* float */
			nil,          /* double */
			nil,          /* [] */
			nil,          /* [ */
			nil,          /* integer */
			nil,          /* ] */
		},
	},
	actionRow{ // S2
		canRecover: false,
		actions: [numSymbols]action{
			nil,      /* INVALID */
			nil,      /* $ */
			nil,      /* package */
			shift(3), /* str */
			nil,      /* empty */
			nil,      /* use */
			nil,      /* class */
			nil,      /* letters */
			nil,      /* { */
			nil,      /* } */
			nil,      /* : */
			nil,      /* struct */
			nil,      /* int */
			nil,      /* int32 */
			nil,      /* int64 */
			nil,      /* long */
			nil,      /* bool */
			nil,      /* short */
			nil,      /* uint */
			nil,      /* uint32 */
			nil,      /* uint64 */
			nil,      /* ulong */
			nil,      /* ubool */
			nil,      /* ushort */
			nil,      /* byte */
			nil,      /* string */
			nil,      /* char */
			nil,      /* float */
			nil,      /* double */
			nil,      /* [] */
			nil,      /* [ */
			nil,      /* integer */
			nil,      /* ] */
		},
	},
	actionRow{ // S3
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(2), /* $, reduce: PackageBody */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			reduce(2), /* use, reduce: PackageBody */
			reduce(2), /* class, reduce: PackageBody */
			nil,       /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			reduce(2), /* struct, reduce: PackageBody */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S4
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(1), /* $, reduce: Package */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			shift(9),  /* use */
			shift(10), /* class */
			nil,       /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			shift(11), /* struct */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S5
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(3), /* $, reduce: PackageBody */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			reduce(3), /* use, reduce: PackageBody */
			reduce(3), /* class, reduce: PackageBody */
			nil,       /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			reduce(3), /* struct, reduce: PackageBody */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S6
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(4), /* $, reduce: PackageElement */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			reduce(4), /* use, reduce: PackageElement */
			reduce(4), /* class, reduce: PackageElement */
			nil,       /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			reduce(4), /* struct, reduce: PackageElement */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S7
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(5), /* $, reduce: PackageElement */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			reduce(5), /* use, reduce: PackageElement */
			reduce(5), /* class, reduce: PackageElement */
			nil,       /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			reduce(5), /* struct, reduce: PackageElement */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S8
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(6), /* $, reduce: PackageElement */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			reduce(6), /* use, reduce: PackageElement */
			reduce(6), /* class, reduce: PackageElement */
			nil,       /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			reduce(6), /* struct, reduce: PackageElement */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S9
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			shift(12), /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			nil,       /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			nil,       /* struct */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S10
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			shift(13), /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			nil,       /* struct */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S11
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			shift(14), /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			nil,       /* struct */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S12
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(7), /* $, reduce: Import */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			reduce(7), /* use, reduce: Import */
			reduce(7), /* class, reduce: Import */
			nil,       /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			reduce(7), /* struct, reduce: Import */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S13
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			nil,       /* letters */
			shift(15), /* { */
			nil,       /* } */
			shift(16), /* : */
			nil,       /* struct */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S14
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			nil,       /* letters */
			shift(17), /* { */
			nil,       /* } */
			shift(18), /* : */
			nil,       /* struct */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S15
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(34), /* letters, reduce: Body */
			nil,        /* { */
			reduce(34), /* }, reduce: Body */
			nil,        /* : */
			nil,        /* struct */
			reduce(34), /* int, reduce: Body */
			reduce(34), /* int32, reduce: Body */
			reduce(34), /* int64, reduce: Body */
			reduce(34), /* long, reduce: Body */
			reduce(34), /* bool, reduce: Body */
			reduce(34), /* short, reduce: Body */
			reduce(34), /* uint, reduce: Body */
			reduce(34), /* uint32, reduce: Body */
			reduce(34), /* uint64, reduce: Body */
			reduce(34), /* ulong, reduce: Body */
			reduce(34), /* ubool, reduce: Body */
			reduce(34), /* ushort, reduce: Body */
			reduce(34), /* byte, reduce: Body */
			reduce(34), /* string, reduce: Body */
			reduce(34), /* char, reduce: Body */
			reduce(34), /* float, reduce: Body */
			reduce(34), /* double, reduce: Body */
			nil,        /* [] */
			nil,        /* [ */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S16
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			shift(20), /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			nil,       /* struct */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S17
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(34), /* letters, reduce: Body */
			nil,        /* { */
			reduce(34), /* }, reduce: Body */
			nil,        /* : */
			nil,        /* struct */
			reduce(34), /* int, reduce: Body */
			reduce(34), /* int32, reduce: Body */
			reduce(34), /* int64, reduce: Body */
			reduce(34), /* long, reduce: Body */
			reduce(34), /* bool, reduce: Body */
			reduce(34), /* short, reduce: Body */
			reduce(34), /* uint, reduce: Body */
			reduce(34), /* uint32, reduce: Body */
			reduce(34), /* uint64, reduce: Body */
			reduce(34), /* ulong, reduce: Body */
			reduce(34), /* ubool, reduce: Body */
			reduce(34), /* ushort, reduce: Body */
			reduce(34), /* byte, reduce: Body */
			reduce(34), /* string, reduce: Body */
			reduce(34), /* char, reduce: Body */
			reduce(34), /* float, reduce: Body */
			reduce(34), /* double, reduce: Body */
			nil,        /* [] */
			nil,        /* [ */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S18
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			shift(22), /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			nil,       /* struct */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S19
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			shift(23), /* letters */
			nil,       /* { */
			shift(24), /* } */
			nil,       /* : */
			nil,       /* struct */
			shift(26), /* int */
			shift(27), /* int32 */
			shift(28), /* int64 */
			shift(29), /* long */
			shift(30), /* bool */
			shift(31), /* short */
			shift(32), /* uint */
			shift(33), /* uint32 */
			shift(34), /* uint64 */
			shift(35), /* ulong */
			shift(36), /* ubool */
			shift(37), /* ushort */
			shift(38), /* byte */
			shift(39), /* string */
			shift(40), /* char */
			shift(41), /* float */
			shift(42), /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S20
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			nil,       /* letters */
			shift(45), /* { */
			nil,       /* } */
			nil,       /* : */
			nil,       /* struct */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S21
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			shift(23), /* letters */
			nil,       /* { */
			shift(46), /* } */
			nil,       /* : */
			nil,       /* struct */
			shift(26), /* int */
			shift(27), /* int32 */
			shift(28), /* int64 */
			shift(29), /* long */
			shift(30), /* bool */
			shift(31), /* short */
			shift(32), /* uint */
			shift(33), /* uint32 */
			shift(34), /* uint64 */
			shift(35), /* ulong */
			shift(36), /* ubool */
			shift(37), /* ushort */
			shift(38), /* byte */
			shift(39), /* string */
			shift(40), /* char */
			shift(41), /* float */
			shift(42), /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S22
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			nil,       /* letters */
			shift(47), /* { */
			nil,       /* } */
			nil,       /* : */
			nil,       /* struct */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S23
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(30), /* letters, reduce: Type */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(30), /* [], reduce: Type */
			reduce(30), /* [, reduce: Type */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S24
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(8), /* $, reduce: ClassDef */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			reduce(8), /* use, reduce: ClassDef */
			reduce(8), /* class, reduce: ClassDef */
			nil,       /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			reduce(8), /* struct, reduce: ClassDef */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S25
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(29), /* letters, reduce: Type */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(29), /* [], reduce: Type */
			reduce(29), /* [, reduce: Type */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S26
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(12), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(12), /* [], reduce: GenericType */
			reduce(12), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S27
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(13), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(13), /* [], reduce: GenericType */
			reduce(13), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S28
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(14), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(14), /* [], reduce: GenericType */
			reduce(14), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S29
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(15), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(15), /* [], reduce: GenericType */
			reduce(15), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S30
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(16), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(16), /* [], reduce: GenericType */
			reduce(16), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S31
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(17), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(17), /* [], reduce: GenericType */
			reduce(17), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S32
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(18), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(18), /* [], reduce: GenericType */
			reduce(18), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S33
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(19), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(19), /* [], reduce: GenericType */
			reduce(19), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S34
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(20), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(20), /* [], reduce: GenericType */
			reduce(20), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S35
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(21), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(21), /* [], reduce: GenericType */
			reduce(21), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S36
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(22), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(22), /* [], reduce: GenericType */
			reduce(22), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S37
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(23), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(23), /* [], reduce: GenericType */
			reduce(23), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S38
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(24), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(24), /* [], reduce: GenericType */
			reduce(24), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S39
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(25), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(25), /* [], reduce: GenericType */
			reduce(25), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S40
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(26), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(26), /* [], reduce: GenericType */
			reduce(26), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S41
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(27), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(27), /* [], reduce: GenericType */
			reduce(27), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S42
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(28), /* letters, reduce: GenericType */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(28), /* [], reduce: GenericType */
			reduce(28), /* [, reduce: GenericType */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S43
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			shift(48), /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			nil,       /* struct */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			shift(49), /* [] */
			shift(50), /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S44
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(35), /* letters, reduce: Body */
			nil,        /* { */
			reduce(35), /* }, reduce: Body */
			nil,        /* : */
			nil,        /* struct */
			reduce(35), /* int, reduce: Body */
			reduce(35), /* int32, reduce: Body */
			reduce(35), /* int64, reduce: Body */
			reduce(35), /* long, reduce: Body */
			reduce(35), /* bool, reduce: Body */
			reduce(35), /* short, reduce: Body */
			reduce(35), /* uint, reduce: Body */
			reduce(35), /* uint32, reduce: Body */
			reduce(35), /* uint64, reduce: Body */
			reduce(35), /* ulong, reduce: Body */
			reduce(35), /* ubool, reduce: Body */
			reduce(35), /* ushort, reduce: Body */
			reduce(35), /* byte, reduce: Body */
			reduce(35), /* string, reduce: Body */
			reduce(35), /* char, reduce: Body */
			reduce(35), /* float, reduce: Body */
			reduce(35), /* double, reduce: Body */
			nil,        /* [] */
			nil,        /* [ */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S45
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(34), /* letters, reduce: Body */
			nil,        /* { */
			reduce(34), /* }, reduce: Body */
			nil,        /* : */
			nil,        /* struct */
			reduce(34), /* int, reduce: Body */
			reduce(34), /* int32, reduce: Body */
			reduce(34), /* int64, reduce: Body */
			reduce(34), /* long, reduce: Body */
			reduce(34), /* bool, reduce: Body */
			reduce(34), /* short, reduce: Body */
			reduce(34), /* uint, reduce: Body */
			reduce(34), /* uint32, reduce: Body */
			reduce(34), /* uint64, reduce: Body */
			reduce(34), /* ulong, reduce: Body */
			reduce(34), /* ubool, reduce: Body */
			reduce(34), /* ushort, reduce: Body */
			reduce(34), /* byte, reduce: Body */
			reduce(34), /* string, reduce: Body */
			reduce(34), /* char, reduce: Body */
			reduce(34), /* float, reduce: Body */
			reduce(34), /* double, reduce: Body */
			nil,        /* [] */
			nil,        /* [ */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S46
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(10), /* $, reduce: StructDef */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			reduce(10), /* use, reduce: StructDef */
			reduce(10), /* class, reduce: StructDef */
			nil,        /* letters */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			reduce(10), /* struct, reduce: StructDef */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			nil,        /* [] */
			nil,        /* [ */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S47
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(34), /* letters, reduce: Body */
			nil,        /* { */
			reduce(34), /* }, reduce: Body */
			nil,        /* : */
			nil,        /* struct */
			reduce(34), /* int, reduce: Body */
			reduce(34), /* int32, reduce: Body */
			reduce(34), /* int64, reduce: Body */
			reduce(34), /* long, reduce: Body */
			reduce(34), /* bool, reduce: Body */
			reduce(34), /* short, reduce: Body */
			reduce(34), /* uint, reduce: Body */
			reduce(34), /* uint32, reduce: Body */
			reduce(34), /* uint64, reduce: Body */
			reduce(34), /* ulong, reduce: Body */
			reduce(34), /* ubool, reduce: Body */
			reduce(34), /* ushort, reduce: Body */
			reduce(34), /* byte, reduce: Body */
			reduce(34), /* string, reduce: Body */
			reduce(34), /* char, reduce: Body */
			reduce(34), /* float, reduce: Body */
			reduce(34), /* double, reduce: Body */
			nil,        /* [] */
			nil,        /* [ */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S48
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(33), /* letters, reduce: VarDecl */
			nil,        /* { */
			reduce(33), /* }, reduce: VarDecl */
			nil,        /* : */
			nil,        /* struct */
			reduce(33), /* int, reduce: VarDecl */
			reduce(33), /* int32, reduce: VarDecl */
			reduce(33), /* int64, reduce: VarDecl */
			reduce(33), /* long, reduce: VarDecl */
			reduce(33), /* bool, reduce: VarDecl */
			reduce(33), /* short, reduce: VarDecl */
			reduce(33), /* uint, reduce: VarDecl */
			reduce(33), /* uint32, reduce: VarDecl */
			reduce(33), /* uint64, reduce: VarDecl */
			reduce(33), /* ulong, reduce: VarDecl */
			reduce(33), /* ubool, reduce: VarDecl */
			reduce(33), /* ushort, reduce: VarDecl */
			reduce(33), /* byte, reduce: VarDecl */
			reduce(33), /* string, reduce: VarDecl */
			reduce(33), /* char, reduce: VarDecl */
			reduce(33), /* float, reduce: VarDecl */
			reduce(33), /* double, reduce: VarDecl */
			nil,        /* [] */
			nil,        /* [ */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S49
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(31), /* letters, reduce: Type */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(31), /* [], reduce: Type */
			reduce(31), /* [, reduce: Type */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S50
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			nil,       /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			nil,       /* struct */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			shift(53), /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S51
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			shift(23), /* letters */
			nil,       /* { */
			shift(54), /* } */
			nil,       /* : */
			nil,       /* struct */
			shift(26), /* int */
			shift(27), /* int32 */
			shift(28), /* int64 */
			shift(29), /* long */
			shift(30), /* bool */
			shift(31), /* short */
			shift(32), /* uint */
			shift(33), /* uint32 */
			shift(34), /* uint64 */
			shift(35), /* ulong */
			shift(36), /* ubool */
			shift(37), /* ushort */
			shift(38), /* byte */
			shift(39), /* string */
			shift(40), /* char */
			shift(41), /* float */
			shift(42), /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S52
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			shift(23), /* letters */
			nil,       /* { */
			shift(55), /* } */
			nil,       /* : */
			nil,       /* struct */
			shift(26), /* int */
			shift(27), /* int32 */
			shift(28), /* int64 */
			shift(29), /* long */
			shift(30), /* bool */
			shift(31), /* short */
			shift(32), /* uint */
			shift(33), /* uint32 */
			shift(34), /* uint64 */
			shift(35), /* ulong */
			shift(36), /* ubool */
			shift(37), /* ushort */
			shift(38), /* byte */
			shift(39), /* string */
			shift(40), /* char */
			shift(41), /* float */
			shift(42), /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S53
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			nil,       /* $ */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			nil,       /* use */
			nil,       /* class */
			nil,       /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			nil,       /* struct */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			shift(56), /* ] */
		},
	},
	actionRow{ // S54
		canRecover: false,
		actions: [numSymbols]action{
			nil,       /* INVALID */
			reduce(9), /* $, reduce: ClassDef */
			nil,       /* package */
			nil,       /* str */
			nil,       /* empty */
			reduce(9), /* use, reduce: ClassDef */
			reduce(9), /* class, reduce: ClassDef */
			nil,       /* letters */
			nil,       /* { */
			nil,       /* } */
			nil,       /* : */
			reduce(9), /* struct, reduce: ClassDef */
			nil,       /* int */
			nil,       /* int32 */
			nil,       /* int64 */
			nil,       /* long */
			nil,       /* bool */
			nil,       /* short */
			nil,       /* uint */
			nil,       /* uint32 */
			nil,       /* uint64 */
			nil,       /* ulong */
			nil,       /* ubool */
			nil,       /* ushort */
			nil,       /* byte */
			nil,       /* string */
			nil,       /* char */
			nil,       /* float */
			nil,       /* double */
			nil,       /* [] */
			nil,       /* [ */
			nil,       /* integer */
			nil,       /* ] */
		},
	},
	actionRow{ // S55
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			reduce(11), /* $, reduce: StructDef */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			reduce(11), /* use, reduce: StructDef */
			reduce(11), /* class, reduce: StructDef */
			nil,        /* letters */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			reduce(11), /* struct, reduce: StructDef */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			nil,        /* [] */
			nil,        /* [ */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
	actionRow{ // S56
		canRecover: false,
		actions: [numSymbols]action{
			nil,        /* INVALID */
			nil,        /* $ */
			nil,        /* package */
			nil,        /* str */
			nil,        /* empty */
			nil,        /* use */
			nil,        /* class */
			reduce(32), /* letters, reduce: Type */
			nil,        /* { */
			nil,        /* } */
			nil,        /* : */
			nil,        /* struct */
			nil,        /* int */
			nil,        /* int32 */
			nil,        /* int64 */
			nil,        /* long */
			nil,        /* bool */
			nil,        /* short */
			nil,        /* uint */
			nil,        /* uint32 */
			nil,        /* uint64 */
			nil,        /* ulong */
			nil,        /* ubool */
			nil,        /* ushort */
			nil,        /* byte */
			nil,        /* string */
			nil,        /* char */
			nil,        /* float */
			nil,        /* double */
			reduce(32), /* [], reduce: Type */
			reduce(32), /* [, reduce: Type */
			nil,        /* integer */
			nil,        /* ] */
		},
	},
}
