// Code generated by "stringer -type=GenericType"; DO NOT EDIT.

package ast

import "strconv"

const _GenericType_name = "Integer32Integer64ShortUnsignedInteger32UnsignedInteger64UnsignedShortByteBoolStringCharFloatDouble"

var _GenericType_index = [...]uint8{0, 9, 18, 23, 40, 57, 70, 74, 78, 84, 88, 93, 99}

func (i GenericType) String() string {
	if i < 0 || i >= GenericType(len(_GenericType_index)-1) {
		return "GenericType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _GenericType_name[_GenericType_index[i]:_GenericType_index[i+1]]
}
