// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"io/ioutil"
	"unicode/utf8"

	"home/dario/repos/shrinken/src/token"
)

const (
	NoState    = -1
	NumStates  = 99
	NumSymbols = 131
)

type Lexer struct {
	src    []byte
	pos    int
	line   int
	column int
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:    src,
		pos:    0,
		line:   1,
		column: 1,
	}
	return lexer
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := ioutil.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	return NewLexer(src), nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = new(token.Token)
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: '"'
1: '"'
2: 'p'
3: 'a'
4: 'c'
5: 'k'
6: 'a'
7: 'g'
8: 'e'
9: 'u'
10: 's'
11: 'e'
12: 'c'
13: 'l'
14: 'a'
15: 's'
16: 's'
17: '{'
18: '}'
19: ':'
20: 's'
21: 't'
22: 'r'
23: 'u'
24: 'c'
25: 't'
26: 'i'
27: 'n'
28: 't'
29: 'i'
30: 'n'
31: 't'
32: '3'
33: '2'
34: 'i'
35: 'n'
36: 't'
37: '6'
38: '4'
39: 'l'
40: 'o'
41: 'n'
42: 'g'
43: 'b'
44: 'o'
45: 'o'
46: 'l'
47: 's'
48: 'h'
49: 'o'
50: 'r'
51: 't'
52: 'u'
53: 'i'
54: 'n'
55: 't'
56: 'u'
57: 'i'
58: 'n'
59: 't'
60: '3'
61: '2'
62: 'u'
63: 'i'
64: 'n'
65: 't'
66: '6'
67: '4'
68: 'u'
69: 'l'
70: 'o'
71: 'n'
72: 'g'
73: 'u'
74: 'b'
75: 'o'
76: 'o'
77: 'l'
78: 'u'
79: 's'
80: 'h'
81: 'o'
82: 'r'
83: 't'
84: 'b'
85: 'y'
86: 't'
87: 'e'
88: 's'
89: 't'
90: 'r'
91: 'i'
92: 'n'
93: 'g'
94: 'c'
95: 'h'
96: 'a'
97: 'r'
98: 'f'
99: 'l'
100: 'o'
101: 'a'
102: 't'
103: 'd'
104: 'o'
105: 'u'
106: 'b'
107: 'l'
108: 'e'
109: '['
110: ']'
111: '['
112: ']'
113: '/'
114: '/'
115: '\n'
116: '/'
117: '*'
118: '*'
119: '*'
120: '/'
121: '_'
122: ' '
123: '\t'
124: '\n'
125: '\r'
126: '1'-'9'
127: '0'-'9'
128: 'a'-'z'
129: 'A'-'Z'
130: .
*/
