// Code generated by gocc; DO NOT EDIT.

package lexer

/*
Let s be the current state
Let r be the current input rune
transitionTable[s](r) returns the next state.
*/
type TransitionTable [NumStates]func(rune) int

var TransTab = TransitionTable{
	// S0
	func(r rune) int {
		switch {
		case r == 9: // ['\t','\t']
			return 1
		case r == 10: // ['\n','\n']
			return 1
		case r == 13: // ['\r','\r']
			return 1
		case r == 32: // [' ',' ']
			return 1
		case r == 34: // ['"','"']
			return 2
		case r == 47: // ['/','/']
			return 3
		case r == 112: // ['p','p']
			return 4
		}
		return NoState
	},
	// S1
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S2
	func(r rune) int {
		switch {
		case r == 34: // ['"','"']
			return 5
		default:
			return 2
		}
	},
	// S3
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 6
		case r == 47: // ['/','/']
			return 7
		}
		return NoState
	},
	// S4
	func(r rune) int {
		switch {
		case r == 97: // ['a','a']
			return 8
		}
		return NoState
	},
	// S5
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S6
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 9
		default:
			return 6
		}
	},
	// S7
	func(r rune) int {
		switch {
		case r == 10: // ['\n','\n']
			return 10
		default:
			return 7
		}
	},
	// S8
	func(r rune) int {
		switch {
		case r == 99: // ['c','c']
			return 11
		}
		return NoState
	},
	// S9
	func(r rune) int {
		switch {
		case r == 42: // ['*','*']
			return 9
		case r == 47: // ['/','/']
			return 12
		default:
			return 6
		}
	},
	// S10
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S11
	func(r rune) int {
		switch {
		case r == 107: // ['k','k']
			return 13
		}
		return NoState
	},
	// S12
	func(r rune) int {
		switch {
		}
		return NoState
	},
	// S13
	func(r rune) int {
		switch {
		case r == 97: // ['a','a']
			return 14
		}
		return NoState
	},
	// S14
	func(r rune) int {
		switch {
		case r == 103: // ['g','g']
			return 15
		}
		return NoState
	},
	// S15
	func(r rune) int {
		switch {
		case r == 101: // ['e','e']
			return 16
		}
		return NoState
	},
	// S16
	func(r rune) int {
		switch {
		}
		return NoState
	},
}
